spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gotech
    username: postgres
    password: srvnata
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
